//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MZcms.Entity
{
    using System;
    using System.Collections.Generic;
    using MZcms.Model;
    using MZcms.CommonModel;
    /// <summary>
    /// ManagerPrivileges
    /// </summary>
    public partial class ManagerPrivileges : BaseModel
    {
    	/// <summary>
        /// 权限自增长ID
        /// </summary>
        public long Id { get; set; }
    	/// <summary>
        /// 权限ID
        /// </summary>
        public int Privilege { get; set; }
    	/// <summary>
        /// 角色ID
        /// </summary>
        public long RoleId { get; set; }
    
         /// <summary>
    	 /// 
         /// </summary>
        public virtual ManagersRoles ManagersRoles { get; set; }
    }
}
