//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MZcms.Entity
{
    using System;
    using System.Collections.Generic;
    using MZcms.Model;
    using MZcms.CommonModel;
    /// <summary>
    /// 管理员日志
    /// </summary>
    public partial class ManagerLog : BaseModel
    {
    	/// <summary>
        /// 日志ID
        /// </summary>
        public long Id { get; set; }
    	/// <summary>
        /// 用户ID
        /// </summary>
        public long UserId { get; set; }
    	/// <summary>
        /// 用户名
        /// </summary>
        public string UserName { get; set; }
    	/// <summary>
        /// 动作类型
        /// </summary>
        public string ActionType { get; set; }
    	/// <summary>
        /// 备注
        /// </summary>
        public string Remark { get; set; }
    	/// <summary>
        /// 用户ID
        /// </summary>
        public string UserIP { get; set; }
    	/// <summary>
        /// 添加日期
        /// </summary>
        public System.DateTime AddDate { get; set; }
    
         /// <summary>
    	 /// 
         /// </summary>
        public virtual Managers Managers { get; set; }
    }
}
