//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MZcms.Entity
{
    using System;
    using System.Collections.Generic;
    using MZcms.Model;
    using MZcms.CommonModel;
    /// <summary>
    /// Managers
    /// </summary>
    public partial class Managers : IPaltManager
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Managers()
        {
            this.ManagerLog = new HashSet<ManagerLog>();
        }
    
    	/// <summary>
        /// 管理员ID
        /// </summary>
        public long Id { get; set; }
    	/// <summary>
        /// 角色ID
        /// </summary>
        public long RoleId { get; set; }
    	/// <summary>
        /// 用户名
        /// </summary>
        public string UserName { get; set; }
    	/// <summary>
        /// 密码
        /// </summary>
        public string Password { get; set; }
    	/// <summary>
        /// 盐值
        /// </summary>
        public string Salt { get; set; }
    	/// <summary>
        /// 头像
        /// </summary>
        public string Avatar { get; set; }
    	/// <summary>
        /// 真名
        /// </summary>
        public string RealName { get; set; }
    	/// <summary>
        /// 手机号
        /// </summary>
        public string Mobile { get; set; }
    	/// <summary>
        /// 添加日期
        /// </summary>
        public System.DateTime AddDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
         /// <summary>
    	 /// 
         /// </summary>
        public virtual ICollection<ManagerLog> ManagerLog { get; set; }
    }
}
