//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MZcms.Entity
{
    using System;
    using System.Collections.Generic;
    using MZcms.Model;
    using MZcms.CommonModel;
    /// <summary>
    /// 站点设置
    /// </summary>
    public partial class SiteSettings : BaseModel
    {
    	/// <summary>
        /// 设置ID
        /// </summary>
        public long Id { get; set; }
    	/// <summary>
        /// 键
        /// </summary>
        public string Key { get; set; }
    	/// <summary>
        /// 值
        /// </summary>
        public string Value { get; set; }
    }
}
