//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MZcms.Entity
{
    using System;
    using System.Collections.Generic;
    using MZcms.Model;
    using MZcms.CommonModel;
    /// <summary>
    /// 用户组
    /// </summary>
    public partial class UserGroups : BaseModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserGroups()
        {
            this.Users = new HashSet<Users>();
        }
    
    	/// <summary>
        /// 会员组ID
        /// </summary>
        public long Id { get; set; }
    	/// <summary>
        /// 名称
        /// </summary>
        public string Title { get; set; }
    	/// <summary>
        /// 等级
        /// </summary>
        public Nullable<int> Grade { get; set; }
    	/// <summary>
        /// 升级需要经验值
        /// </summary>
        public Nullable<int> UpgradeExp { get; set; }
    	/// <summary>
        /// 预存金额
        /// </summary>
        public Nullable<decimal> Amount { get; set; }
    	/// <summary>
        /// 默认积分
        /// </summary>
        public Nullable<int> Point { get; set; }
    	/// <summary>
        /// 是否默认
        /// </summary>
        public bool IsDefault { get; set; }
    	/// <summary>
        /// 是否自动升级
        /// </summary>
        public bool IsUpgrade { get; set; }
    	/// <summary>
        /// 是否锁定
        /// </summary>
        public bool IsLock { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
         /// <summary>
    	 /// 
         /// </summary>
        public virtual ICollection<Users> Users { get; set; }
    }
}
